<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy" data-toc-modified-id="Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy</a></span></li><li><span><a href="#Basics" data-toc-modified-id="Basics-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Basics</a></span></li><li><span><a href="#Arrays" data-toc-modified-id="Arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Arrays</a></span><ul class="toc-item"><li><span><a href="#Creation" data-toc-modified-id="Creation-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Creation</a></span><ul class="toc-item"><li><span><a href="#from-list/tuple" data-toc-modified-id="from-list/tuple-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>from list/tuple</a></span></li><li><span><a href="#arange()" data-toc-modified-id="arange()-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>arange()</a></span></li><li><span><a href="#zeros()" data-toc-modified-id="zeros()-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>zeros()</a></span></li><li><span><a href="#ones()" data-toc-modified-id="ones()-3.1.4"><span class="toc-item-num">3.1.4&nbsp;&nbsp;</span>ones()</a></span></li><li><span><a href="#full()" data-toc-modified-id="full()-3.1.5"><span class="toc-item-num">3.1.5&nbsp;&nbsp;</span>full()</a></span></li><li><span><a href="#eye()" data-toc-modified-id="eye()-3.1.6"><span class="toc-item-num">3.1.6&nbsp;&nbsp;</span>eye()</a></span></li><li><span><a href="#random()" data-toc-modified-id="random()-3.1.7"><span class="toc-item-num">3.1.7&nbsp;&nbsp;</span>random()</a></span></li><li><span><a href="#empty()" data-toc-modified-id="empty()-3.1.8"><span class="toc-item-num">3.1.8&nbsp;&nbsp;</span>empty()</a></span></li><li><span><a href="#empty_like()" data-toc-modified-id="empty_like()-3.1.9"><span class="toc-item-num">3.1.9&nbsp;&nbsp;</span>empty_like()</a></span></li></ul></li><li><span><a href="#Attributes" data-toc-modified-id="Attributes-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Attributes</a></span><ul class="toc-item"><li><span><a href="#shape" data-toc-modified-id="shape-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>shape</a></span></li><li><span><a href="#ndim" data-toc-modified-id="ndim-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>ndim</a></span></li><li><span><a href="#dtype" data-toc-modified-id="dtype-3.2.3"><span class="toc-item-num">3.2.3&nbsp;&nbsp;</span>dtype</a></span></li></ul></li><li><span><a href="#Indexing-/-slicing" data-toc-modified-id="Indexing-/-slicing-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Indexing / slicing</a></span></li><li><span><a href="#Shape-manipulation" data-toc-modified-id="Shape-manipulation-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Shape manipulation</a></span><ul class="toc-item"><li><span><a href="#ravel()" data-toc-modified-id="ravel()-3.4.1"><span class="toc-item-num">3.4.1&nbsp;&nbsp;</span>ravel()</a></span></li><li><span><a href="#transpose" data-toc-modified-id="transpose-3.4.2"><span class="toc-item-num">3.4.2&nbsp;&nbsp;</span>transpose</a></span></li><li><span><a href="#stack" data-toc-modified-id="stack-3.4.3"><span class="toc-item-num">3.4.3&nbsp;&nbsp;</span>stack</a></span><ul class="toc-item"><li><span><a href="#hstack()" data-toc-modified-id="hstack()-3.4.3.1"><span class="toc-item-num">3.4.3.1&nbsp;&nbsp;</span>hstack()</a></span></li><li><span><a href="#vstack()" data-toc-modified-id="vstack()-3.4.3.2"><span class="toc-item-num">3.4.3.2&nbsp;&nbsp;</span>vstack()</a></span></li><li><span><a href="#dstack()" data-toc-modified-id="dstack()-3.4.3.3"><span class="toc-item-num">3.4.3.3&nbsp;&nbsp;</span>dstack()</a></span></li></ul></li><li><span><a href="#reshape()" data-toc-modified-id="reshape()-3.4.4"><span class="toc-item-num">3.4.4&nbsp;&nbsp;</span>reshape()</a></span></li><li><span><a href="#resize()" data-toc-modified-id="resize()-3.4.5"><span class="toc-item-num">3.4.5&nbsp;&nbsp;</span>resize()</a></span></li></ul></li><li><span><a href="#Datatypes" data-toc-modified-id="Datatypes-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Datatypes</a></span></li><li><span><a href="#Array-math" data-toc-modified-id="Array-math-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Array math</a></span><ul class="toc-item"><li><span><a href="#element-wise-operations" data-toc-modified-id="element-wise-operations-3.6.1"><span class="toc-item-num">3.6.1&nbsp;&nbsp;</span>element-wise operations</a></span></li><li><span><a href="#dot-product" data-toc-modified-id="dot-product-3.6.2"><span class="toc-item-num">3.6.2&nbsp;&nbsp;</span>dot product</a></span></li><li><span><a href="#broadcasting" data-toc-modified-id="broadcasting-3.6.3"><span class="toc-item-num">3.6.3&nbsp;&nbsp;</span>broadcasting</a></span></li></ul></li><li><span><a href="#Copies-and-Views" data-toc-modified-id="Copies-and-Views-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Copies and Views</a></span><ul class="toc-item"><li><span><a href="#no-copy" data-toc-modified-id="no-copy-3.7.1"><span class="toc-item-num">3.7.1&nbsp;&nbsp;</span>no copy</a></span></li><li><span><a href="#shallow-copy:-view()" data-toc-modified-id="shallow-copy:-view()-3.7.2"><span class="toc-item-num">3.7.2&nbsp;&nbsp;</span>shallow copy: view()</a></span></li><li><span><a href="#deep-copy:-copy()" data-toc-modified-id="deep-copy:-copy()-3.7.3"><span class="toc-item-num">3.7.3&nbsp;&nbsp;</span>deep copy: copy()</a></span></li></ul></li><li><span><a href="#Printing" data-toc-modified-id="Printing-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>Printing</a></span></li></ul></li></ul></div>

<font size="5"><b>NUMPY tutorial</b></font>

Several numpy tutorials can be found [here](https://numpy.org/learn/)

# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.  

For MATLAB users, consider consulting the Numpy's [NumPy for Matlab Users](http://wiki.scipy.org/NumPy_for_Matlab_Users) page.

# Basics

Numpy’s main object is the multidimensional `numpy array`:<br>
    => it is a table of elements (usually numbers), <u>all of the same type</u>, indexed by a tuple of non-negative integers<br>
    => array dimensions are called `axes`<br>
    => the number of dimensions is called the array `rank`<br>
    => numpy's array class is called `ndarray` 

Import the `numpy` package as follows:

In [2]:
import numpy as np

# Arrays

## Creation

### from list/tuple
Create arrays from a sequence of values (Python list or tuple).

In [11]:
# create from a sequence of values (Python list or tuple):
a = np.array([0, 1, 2]) #>> create from list
a = np.array((0, 1, 2)) #>> create from tuple

print(type(a))
a

<class 'numpy.ndarray'>


array([0, 1, 2])

In [26]:
# create multi-dimentional arrays from nested lists
nested_list = [[1,2,3],[4,5,6]]
a = np.array(nested_list)

a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# specify data type upon creation
a = np.array([1, 2, 3], dtype='uint8')
print(a.dtype)

a = np.array([1, 2, 3], dtype='float32')
print(a.dtype)

a = np.array(['1', '2', '3'])
print(a.dtype)

uint8
float32
<U1


### arange()
Create a 1D array of values, specifying the `start`, `stop`, `step`. The arange function is analogous to the Python built-in range, <u>but returns an array</u>.

In [24]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


**Arange can be combined with the `reshape()` function to create multidimensional arrays:**

In [34]:
b = np.arange(12).reshape(4, 3)     # 2d array (12 elements, arranged as 4 rows x 3 columns)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [66]:
# WARNING: in the following example, the 3D array is filled sequentially, parsing the values through the various channels 
# => does NOT fill a channel before going to the next) 
# => in this case the first channel has values 0, 4, 8, 12, 16, 20 (since there are 4 channels in array)

c = np.arange(24).reshape(2, 3, 4)  # 3d array (24 elements, arranged as 4 matrices of 2 rows x 3 columns)
print(c)

print(c[:,:,0])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  4  8]
 [12 16 20]]


### zeros()
Create an array of zeros, specifying the array shape as a tuple.

In [21]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones()
Create an array of ones, specifying the array shape as a tuple.

In [22]:
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### full()
Create an array of unique values, specifying the array shape as a tuple.

In [67]:
a = np.full((2,2), 7)
print(a)

[[7 7]
 [7 7]]


### eye()
Create the identity matrix, specifying the array shape as a tuple.

In [69]:
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


### random()
Create an array of random floats in the range [0-1], specifying the array shape as a tuple.

In [73]:
a = np.random.random((2,2)) # Create an array filled with random values
print(a)

[[0.43048459 0.06487667]
 [0.87162144 0.11032227]]


### empty()
Creates an array whose initial content is random and depends on the state of the memory. 

In [108]:
a = np.empty((2,2))
a

array([[0.51020597, 0.58265003],
       [0.49145982, 0.48806746]])

### empty_like()
Create an empty array with the same shape as a.

In [107]:
a = np.ones((2,2))

b = np.empty_like(a)   # Create an empty matrix with the same shape as x
b

array([[0.51020597, 0.58265003],
       [0.49145982, 0.48806746]])

## Attributes
The most important attributes are `shape` and `dtype`. (See [here](https://numpy.org/devdocs/user/quickstart.html) for a more complete list).

In [44]:
# create 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

### shape
Returns the dimensions of the array as a tuple of integers:<br>
`(nb_rows, nb_columns)` for 2D arrays, `(nb_rows, nb_columns, nb_channels)` for 3D arrays

In [31]:
a.shape

(2, 3)

### ndim
Returns the number of `dimensions` of the array. 

In [46]:
a.ndim

2

In [47]:
len(a.shape) # >> equivalent to asking for the length of the array shape

2

### dtype
Returns the type of the elements in the array. 

In [32]:
a.dtype

dtype('int64')

## Indexing / slicing

Numpy offers `indexing` and `slicing`, similar to Python lists:<br> 
- access elements using square brackets
- Python is zero-based, meaning the first element is accessed with the index 0<br>
- the result of the slicing includes the start index, but excludes the end index

However because arrays may be multidimensional, you must specify a slice for each dimension of the array:
- `array[rows, cols, channels]`

In [4]:
# --- REMINDER: indexing/slicing Python lists
l = [1, 2, 3, 4, 5] # create list

# - access single element
l[0]                # access first element
l[-1]               # access last element
l[-2]               # access second to last element

# - slice (access multiple elements)
# Important: the result includes the start index, but excludes the end index
l[1:3]              # access 2nd & 3rd elements
l[1:-2]             # access 2nd until 2nd to last element
l[:3]               # access all elements from start until 4th element
l[3:]               # access all elements from 4th element until end
l[::2]              # access every nth element

# - assign element
l[0] = 0            # replace element
l[1:2] = [-1, -2]   # assign a sublist to a slice

In [42]:
# --- 1D numpy array
# => index/slice array just like a list

a = np.arange(6)    # create 1D array
print(a)
print(a[0])         # access first element
print(a[1:3])       # access 2nd & 4th elements

[0 1 2 3 4 5]
0
[1 2]


In [54]:
# --- 2D numpy array
# => specify a slice for each dimension of the array

b = np.arange(12).reshape(4, 3)     # create 2D array (12 elements, arranged as 4 rows x 3 columns)
print(b)

b[:, 0]       # access all row elements from the first column
b[-1, -2:]    # access the last 2 elements from the last row

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([10, 11])

In [76]:
# --- 3D numpy array

# WARNING: in the following example, the 3D array is filled sequentially, parsing the values through the various channels 
# => does NOT fill a channel before going to the next) 
# => in this case the first channel has values 0, 4, 8, 12, 16, 20 (since there are 4 channels in array)

c = np.arange(24).reshape(2, 3, 4)  # create 3d array (24 elements, arranged as 4 matrices of 2 rows x 3 columns)
print(c)

c[:, :, 0]       # access all rows and columns from the first channel
c[..., 0]        # (equivalent to above command)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 0,  4,  8],
       [12, 16, 20]])

**Boolean indexing**

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


## Shape manipulation

### ravel()
Returns the array, flattened.

In [80]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

a.ravel()

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

### transpose

In [81]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

a.T

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

### stack

#### hstack()
Stack arrays horizontally.

In [88]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6])

#### vstack()
Stack arrays vertically.

In [89]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
c

array([[1, 2, 3],
       [4, 5, 6]])

#### dstack()
Stack arrays depth-wise.<br>
(Useful to create RGB arrays from distinct R, G, B channels.)

In [93]:
R = np.zeros((3, 3))     # create 1st channel with 0
G = np.ones((3, 3))      # create 2nd channel with 1
B = np.full((3, 3), 10)  # create 3rd channel with 10

In [97]:
RGB = np.dstack((R, G, B))
RGB

array([[[ 0.,  1., 10.],
        [ 0.,  1., 10.],
        [ 0.,  1., 10.]],

       [[ 0.,  1., 10.],
        [ 0.,  1., 10.],
        [ 0.,  1., 10.]],

       [[ 0.,  1., 10.],
        [ 0.,  1., 10.],
        [ 0.,  1., 10.]]])

### reshape()

In [82]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

a.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

### resize()

In [87]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

a.resize((3, 2))
a

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

## Datatypes

<u>Every numpy array is a grid of elements of the same type</u>.<br>
You can explicitly specify the datatype when creating an array. <br>

See numpy documentation about all numpy datatypes [here](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

In [99]:
x = np.array([1, 2])                  # dtype not specified => guessed by numpy => int
y = np.array([1.0, 2.0])              # dtype not specified => guessed by numpy => float
z = np.array([1, 2], dtype=np.uint8)  # dtype specified

print(x.dtype, y.dtype, z.dtype)

int64 float64 uint8


## Array math

<u>Arithmetic operators on arrays apply `elementwise`</u>. A new array is created and filled with the result.<br>
Basic mathematical functions are alse available as functions in the numpy module (ex: `np.add()`, etc.). See the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

<u>Note</u>: unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. Numpy uses instead the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.

### element-wise operations

In [102]:
# --- create arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [101]:
# --- elementwise sum
print(x + y)
print(np.add(x, y)) #>> equivalent result

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
# --- elementwise difference
print(x - y)
print(np.subtract(x, y)) #>> equivalent result

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# --- elementwise product
print(x * y)
print(np.multiply(x, y)) #>> equivalent result

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [103]:
# --- elementwise division
print(x / y)
print(np.divide(x, y)) #>> equivalent result

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [104]:
# --- elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### dot product

In [100]:
# --- dot product 
# NB: unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. Numpy uses instead the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

**Example**: add a constant vector to each row of a matrix

In [ ]:
# => add vector v to each row of the matrix x, storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

## Copies and Views

<u>When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not</u>.<br>

There are three cases.

### no copy
Simple assignments make no copy of objects or their data.

In [132]:
a = np.ones((5, 5), dtype='uint8')

b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

### shallow copy: view()
Different array objects can share the same data. The `view` method creates a new array object that looks at the same data.

In [136]:
a = np.ones((5, 5), dtype='uint8')
a_shallow = a.view()          # make shallow copy: ``a_deep`` is a 'view' of the data owned by a

print(a_shallow is a)
print(a_shallow.base is a )

False
True


In [137]:
a_shallow[0, 0] = 100         # a's data changes
a

array([[100,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1]], dtype=uint8)

In [133]:
a_shallow = a_shallow.reshape((1, 25))  # a's shape doesn't change
a.shape

(5, 5)

In [134]:
# Slicing an array returns a view of it:

s = a[:, 1:3]
s[:] = 10  # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
a

array([[ 1, 10, 10,  1,  1],
       [ 1, 10, 10,  1,  1],
       [ 1, 10, 10,  1,  1],
       [ 1, 10, 10,  1,  1],
       [ 1, 10, 10,  1,  1]], dtype=uint8)

### deep copy: copy()
The copy method makes a complete copy of the array and its data.

In [138]:
a = np.ones((5, 5), dtype='uint8')
a_deep = a.copy()        # a new array ``a_deep`` with new data is created

print(a_deep is a)
print(a_deep.base is a)  # a_deep doesn't share anything with a

a_deep[0, 0] = 9999      # changing the deep copy does not change the original variable
a

False
False


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [ ]:
del a  # the memory of ``a`` can be released

## Printing
When you print an array, NumPy displays it in a similar way to nested lists.  
(In the case of large arrays, it prints the first and last elements only.)

In [33]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


In [34]:
b = np.arange(12).reshape(4, 3)     # 2d array (12 elements, arranged as 4 rows, 3 columns)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array (24 elements, arranged as 4 matrices of 2 rows and 3 columns)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
